/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaDTO { 
    /**
     * URL pública de la imagen en S3.
     */
    url?: string;
    fileName?: string;
    /**
     * Tamaño en bytes.
     */
    size?: number;
}

