/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyDTO } from './propertyDTO';


export interface PagePropertyDTO { 
    content?: Array<PropertyDTO>;
    totalElements?: number;
    totalPages?: number;
    size?: number;
    number?: number;
}

