/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaDTO } from './mediaDTO';
import { PropertyDTOLocation } from './propertyDTOLocation';
import { UserProfileDTO } from './userProfileDTO';
import { PropertyDetailDTOAllOfFeatures } from './propertyDetailDTOAllOfFeatures';


export interface PropertyDetailDTO { 
    id?: string;
    title?: string;
    description?: string;
    price?: number;
    type?: PropertyDetailDTO.TypeEnum;
    location?: PropertyDTOLocation;
    /**
     * URL de la primera imagen de la propiedad (thumbnail para listados)
     */
    thumbnailUrl?: string;
    createdAt?: string;
    owner?: UserProfileDTO;
    fullAddress?: string;
    features?: PropertyDetailDTOAllOfFeatures;
    mediaPreviews?: Array<MediaDTO>;
    /**
     * Score mínimo de solvencia requerido por el propietario
     */
    minSolvencyScore?: number;
}
export namespace PropertyDetailDTO {
    export const TypeEnum = {
        Rent: 'RENT',
        Sale: 'SALE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


