/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropertyCreateDTOFeatures { 
    rooms?: number;
    bathrooms?: number;
    surface?: number;
    hasElevator?: boolean;
    hasParking?: boolean;
    energyCertificate?: PropertyCreateDTOFeatures.EnergyCertificateEnum;
}
export namespace PropertyCreateDTOFeatures {
    export const EnergyCertificateEnum = {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
        E: 'E',
        F: 'F',
        G: 'G'
    } as const;
    export type EnergyCertificateEnum = typeof EnergyCertificateEnum[keyof typeof EnergyCertificateEnum];
}


