/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyDTOLocation } from './propertyDTOLocation';
import { PropertyCreateDTOFeatures } from './propertyCreateDTOFeatures';


export interface PropertyCreateDTO { 
    title: string;
    description?: string;
    price: number;
    type: PropertyCreateDTO.TypeEnum;
    location: PropertyDTOLocation;
    mediaIds?: Array<string>;
    features?: PropertyCreateDTOFeatures;
}
export namespace PropertyCreateDTO {
    export const TypeEnum = {
        Rent: 'RENT',
        Sale: 'SALE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


