/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyDTOLocation } from './propertyDTOLocation';


export interface PropertyDTO { 
    id?: string;
    title?: string;
    description?: string;
    price?: number;
    type?: PropertyDTO.TypeEnum;
    location?: PropertyDTOLocation;
    /**
     * URL de la primera imagen de la propiedad (thumbnail para listados)
     */
    thumbnailUrl?: string;
    createdAt?: string;
}
export namespace PropertyDTO {
    export const TypeEnum = {
        Rent: 'RENT',
        Sale: 'SALE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


