/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewTokenInfoDTO { 
    eventType?: ReviewTokenInfoDTO.EventTypeEnum;
    toUserName?: string;
    propertyId?: string;
    expiresAt?: string;
    expectedDimensions?: Array<string>;
}
export namespace ReviewTokenInfoDTO {
    export const EventTypeEnum = {
        Visit: 'VISIT',
        Contract: 'CONTRACT'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


