/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewDTO { 
    id?: string;
    eventType?: ReviewDTO.EventTypeEnum;
    dimensions?: { [key: string]: number; };
    visibleAt?: string | null;
    disputed?: boolean;
    createdAt?: string;
}
export namespace ReviewDTO {
    export const EventTypeEnum = {
        Visit: 'VISIT',
        Contract: 'CONTRACT'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


