/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewTokenDTO { 
    id?: string;
    token?: string;
    eventType?: ReviewTokenDTO.EventTypeEnum;
    weight?: number;
    expiresAt?: string;
    usedAt?: string | null;
}
export namespace ReviewTokenDTO {
    export const EventTypeEnum = {
        Visit: 'VISIT',
        Contract: 'CONTRACT'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


