/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewTokenCreateRequest { 
    eventType: ReviewTokenCreateRequest.EventTypeEnum;
    fromUserId: string;
    toUserId: string;
    propertyId: string;
}
export namespace ReviewTokenCreateRequest {
    export const EventTypeEnum = {
        Visit: 'VISIT',
        Contract: 'CONTRACT'
    } as const;
    export type EventTypeEnum = typeof EventTypeEnum[keyof typeof EventTypeEnum];
}


