/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertySearchRequest } from './propertySearchRequest';


export interface SavedSearchCreateRequest { 
    name: string;
    filters: PropertySearchRequest;
}

