/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertySearchRequest } from './propertySearchRequest';


export interface SavedSearchDTO { 
    id?: string;
    name?: string;
    filters?: PropertySearchRequest;
    active?: boolean;
    lastCheckedAt?: string;
    createdAt?: string;
}

