/**
 * PropTech API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileDTO { 
    id?: string;
    email?: string;
    name?: string;
    trustScore?: number;
    isVerified?: boolean;
    solvencyScore?: number | null;
    solvencyVerifiedAt?: string | null;
    solvencyContractType?: UserProfileDTO.SolvencyContractTypeEnum | null;
}
export namespace UserProfileDTO {
    export const SolvencyContractTypeEnum = {
        Indefinido: 'INDEFINIDO',
        Temporal: 'TEMPORAL',
        Obra: 'OBRA'
    } as const;
    export type SolvencyContractTypeEnum = typeof SolvencyContractTypeEnum[keyof typeof SolvencyContractTypeEnum];
}


