spring.application.name=proptech-api

spring.datasource.url=jdbc:postgresql://localhost:5432/proptech_db
spring.datasource.username=proptech_user
spring.datasource.password=proptech_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS10aGF0LW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHM=
jwt.expiration=86400000
